# fly.toml app configuration file generated for backend-summer-glade-2820 on 2025-01-21T09:20:52-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'backend-summer-glade-2820'
primary_region = 'scl'

[build]

[env]
  PORT = "3000" 

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
